Milestone:2 Microverse project HTML Forms
talhawaqar/html-forms- pull request #1
Opened 2020-05-04 13:50 UTC by talhawaqar

Create mint.com signup form replica according to the requirements of Microverse

2020-05-04 20:26 UTC, addod19 commented
## Pull  Request under review by Daniel Larbi Addo (TSE)

2020-05-04 20:44 UTC, addod19 requested changes
## Status: Require changes :recycle: :traffic_light: 

Hi @talhawaqar and @visva-dev, congratulations on a great job done :+1:  Let us improve our code and make it even better by fixing the comments below:
- Kindly enable stickler for the repo by visiting stickler-ci.com
- Kindly change the type of the input to ```tel``` ``` <input type="number" name="phone" id="phone" />```
- Currently, the page is missing a ```<footer>``` let us include the ```<footer>```
- Let us apply the DRY rule to our CSS file, kindly read [this](https://speckyboy.com/good-bad-css-practices/) for more insight
- Kindly add emails and twitter handles to our README file

Kindly make these changes and submit another code review :smile: 
_Happy coding_ :man_technologist: 
Daniel Larbi Addo on slack

2020-05-04 20:44 UTC, addod19 commented on index.html
> +              <p class="phone-note">Standard call, messaging or data rates may apply.</p>
Let us improve semantics by using ```<main>``` instead of ```<div class="main-form">```

2020-05-05 23:18 UTC, mikenath223 commented
### Pull request currently under review by Michgolden Ukeje (TSE).
Kindly exercise patience 👋

2020-05-05 23:27 UTC, mikenath223 approved these changes
### Hi Team 👋

You both have done quite well on this project @talhawaqar and @visva-dev  👍

This project meets the requirements for approval.

**STATUS: APPROVED ✅**


Don't forget to fill the project completion form👍
Good luck with the next project.

HAPPY CODING👨‍💻

2020-05-06 05:59 UTC, merged